
version: '3'

services:
  mariadb:
    container_name: l2j-server-mariadb
    image: yobasystems/alpine-mariadb:latest
    volumes:
      - /var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
  l2jserver:
    container_name: l2j-server-docker
    image: l2jserver/l2j-server-docker:latest
    restart: always
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     branch_gs: "develop"
    #     branch_dp: "develop"
    environment:
      IP_ADDRESS: ${GAMESERVER_ADDRESS}
      RATE_XP: "1"
      RATE_SP: "1"
      ADMIN_RIGHTS: "True"
      HELLBOUND_ACCESS: "True"
      TVT_ENABLED: "True"
      FORCE_GEODATA: "False"
      COORD_SYNC: "-1"
      BUFFER_SERVICE: "True"
      CUSTOM_NPC_DATA: "True"
      SAVE_GM_SPAWN_ON_CUSTOM: "True"
      CUSTOM_SPAWNLIST_TABLE: "True"
      CUSTOM_TELEPORT_TABLE: "True"
      CUSTOM_NPC_BUFFER_TABLES: "True"
      CUSTOM_SKILLS_LOAD: "True"
      CUSTOM_ITEMS_LOAD: "True"
      CUSTOM_MULTISELL_LOAD: "True"
      CUSTOM_BUYLIST_LOAD: "True"
    depends_on:
      - mariadb
    ports:
      - 7777:7777
      - 2106:2106
  nginx:
    build: './nginx'
    volumes:
      - ./nginx-public_html:/home/public_html
    ports:
      - 8000:80
    depends_on:
      - php-apache
  php-apache:
    build: './php-apache'
    ports:
      - 8001:8001
    volumes:
      - ./public_html:/home/public_html
    env_file: ./.env
    depends_on:
      - mariadb
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    restart: always
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
    - mariadb    
